spring:
  application:
    name: sender-service
server:
    port: ${SERVER_PORT}

webhook:
  receiver:
    url: ${WEBHOOK_RECEIVER_URL}
  secret: ${WEBHOOK_SECRET}

logging:
  level:
    br.com.danilodps.sender: DEBUG